# Generated by Django 5.0.4 on 2024-04-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCVapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
