# Generated by Django 5.0.4 on 2024-04-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCVapp', '0002_certificate_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='Time4 Digital', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='Tychy', max_length=100),
            preserve_default=False,
        ),
    ]
